### ISSUE TITLE
cactus-pull-all-submodules fails

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#28] opened 2022-08-11 23:37 UTC
This script fails to pull changes:

```
[~/Workspaces/telenav-build/kivakit-extensions] git status
On branch develop
Your branch is behind 'origin/develop' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
```

 into kivakit-extensions and other projects because apparently it skips the mojo according to this output for each project:

```
[INFO] Skipping PullMojo mojo per policy last-containing-goal
```

. Without the --quiet switch this is the output:

```
[~/Workspaces/telenav-build] mvn -Dcactus.scope=ALL -Dcactus.include-root=false com.telenav.cactus:cactus-maven-plugin:1.5.22:pull
[INFO] Scanning for projects...

[snip]

[INFO]
[INFO] -----------------< com.telenav:telenav-root-superpom >------------------
[INFO] Building telenav-root-superpom 1.0.2                             [1/176]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- cactus-maven-plugin:1.5.22:pull (default-cli) @ telenav-root-superpom ---
[INFO] Skipping PullMojo mojo per policy last-containing-goal
[INFO]
[INFO] --------------------< com.telenav:telenav-superpom >--------------------
[INFO] Building telenav-superpom 2.0.3                                  [2/176]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- cactus-maven-plugin:1.5.22:pull (default-cli) @ telenav-superpom ---
[INFO] Skipping PullMojo mojo per policy last-containing-goal
[INFO]
[INFO] ------------< com.telenav:telenav-superpom-project-family >-------------
[INFO] Building telenav-superpom-project-family 2.0.3                   [3/176]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- cactus-maven-plugin:1.5.22:pull (default-cli) @ telenav-superpom-project-family ---
[INFO] Skipping PullMojo mojo per policy last-containing-goal
[INFO]
[INFO] ---------------------< com.telenav.cactus:cactus >----------------------
[INFO] Building cactus 1.5.23                                           [4/176]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- cactus-maven-plugin:1.5.22:pull (default-cli) @ cactus ---
[INFO] Skipping PullMojo mojo per policy last-containing-goal
[INFO]
[INFO] ----------------< com.telenav.cactus:cactus-maven-log >-----------------
[INFO] Building cactus-maven-log 1.5.23                                 [5/176]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- cactus-maven-plugin:1.5.22:pull (default-cli) @ cactus-maven-log ---
[INFO] Skipping PullMojo mojo per policy last-containing-goal
[INFO]
[INFO] -------------------< com.telenav.cactus:cactus-util >-------------------
[INFO] Building cactus-util 1.5.23                                      [6/176]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- cactus-maven-plugin:1.5.22:pull (default-cli) @ cactus-util ---
[INFO] Skipping PullMojo mojo per policy last-containing-goal
[INFO]
[INFO] -------------------< com.telenav.cactus:cactus-cli >--------------------
[INFO] Building cactus-cli 1.5.23                                       [7/176]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- cactus-maven-plugin:1.5.22:pull (default-cli) @ cactus-cli ---
[INFO] Skipping PullMojo mojo per policy last-containing-goal
[INFO]
[INFO] -------------------< com.telenav.cactus:cactus-git >--------------------
[INFO] Building cactus-git 1.5.23                                       [8/176]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- cactus-maven-plugin:1.5.22:pull (default-cli) @ cactus-git ---
[INFO] Skipping PullMojo mojo per policy last-containing-goal
[INFO]
[INFO] -----------------< com.telenav.cactus:cactus-metadata >-----------------
[INFO] Building cactus-metadata 1.5.23                                  [9/176]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- cactus-maven-plugin:1.5.22:pull (default-cli) @ cactus-metadata ---
[INFO] Skipping PullMojo mojo per policy last-containing-goal
[INFO]
[INFO] ----------------< com.telenav.cactus:cactus-maven-xml >-----------------
[INFO] Building cactus-maven-xml 1.5.23                                [10/176]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- cactus-maven-plugin:1.5.22:pull (default-cli) @ cactus-maven-xml ---
[INFO] Skipping PullMojo mojo per policy last-containing-goal
[INFO]

[snip]

[INFO] --- cactus-maven-plugin:1.5.22:pull (default-cli) @ telenav-build ---
[INFO] Nothing to pull. All projects are up to date with remote.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] telenav-root-superpom 1.0.2 ........................ SUCCESS [  0.120 s]
[INFO] telenav-superpom 2.0.3 ............................. SUCCESS [  0.002 s]
[INFO] telenav-superpom-project-family 2.0.3 .............. SUCCESS [  0.002 s]
[INFO] cactus 1.5.23 ...................................... SUCCESS [  0.001 s]
[INFO] cactus-maven-log 1.5.23 ............................ SUCCESS [  0.001 s]
[INFO] cactus-util 1.5.23 ................................. SUCCESS [  0.002 s]
[INFO] cactus-cli 1.5.23 .................................. SUCCESS [  0.001 s]
[INFO] cactus-git 1.5.23 .................................. SUCCESS [  0.001 s]
[INFO] cactus-metadata 1.5.23 ............................. SUCCESS [  0.001 s]
[INFO] cactus-maven-xml 1.5.23 ............................ SUCCESS [  0.000 s]
[INFO] cactus-maven-model 1.5.23 .......................... SUCCESS [  0.001 s]
[INFO] cactus-scope 1.5.23 ................................ SUCCESS [  0.001 s]
[INFO] cactus-maven-versioning 1.5.23 ..................... SUCCESS [  0.001 s]
[INFO] cactus-codeflowers 1.5.23 .......................... SUCCESS [  0.001 s]
[INFO] cactus-maven-plugin 1.5.23 ......................... SUCCESS [  0.002 s]
[INFO] telenav-superpom-project 2.0.4 ..................... SUCCESS [  0.007 s]
[INFO] telenav-superpom-kivakit 2.0.6 ..................... SUCCESS [  0.015 s]
[INFO] telenav-superpom-mesakit 2.0.6 ..................... SUCCESS [  0.001 s]
[INFO] telenav-superpom-lexakai 2.0.6 ..................... SUCCESS [  0.001 s]
[INFO] telenav-superpom-intermediate-bom 2.0.1 ............ SUCCESS [  0.000 s]
[INFO] telenav-superpom-bom 2.0.1 ......................... SUCCESS [  0.054 s]
[INFO] lexakai-annotations 1.0.5-SNAPSHOT ................. SUCCESS [  0.001 s]
[INFO] kivakit-interfaces 1.6.3-SNAPSHOT .................. SUCCESS [  0.001 s]
[INFO] kivakit-mixins 1.6.3-SNAPSHOT ...................... SUCCESS [  0.001 s]
[INFO] kivakit-core 1.6.3-SNAPSHOT ........................ SUCCESS [  0.002 s]
[INFO] kivakit-internal-testing 1.6.3-SNAPSHOT ............ SUCCESS [  0.001 s]
[INFO] kivakit-collections 1.6.3-SNAPSHOT ................. SUCCESS [  0.001 s]
[INFO] kivakit-conversion 1.6.3-SNAPSHOT .................. SUCCESS [  0.001 s]
[INFO] kivakit-extraction 1.6.3-SNAPSHOT .................. SUCCESS [  0.001 s]
[INFO] kivakit-validation 1.6.3-SNAPSHOT .................. SUCCESS [  0.001 s]
[INFO] kivakit-commandline 1.6.3-SNAPSHOT ................. SUCCESS [  0.001 s]
[INFO] kivakit-resource 1.6.3-SNAPSHOT .................... SUCCESS [  0.002 s]
[INFO] kivakit-serialization-core 1.6.3-SNAPSHOT .......... SUCCESS [  0.001 s]
[INFO] kivakit-serialization-properties 1.6.3-SNAPSHOT .... SUCCESS [  0.000 s]
[INFO] kivakit-serialization-kryo 1.6.3-SNAPSHOT .......... SUCCESS [  0.002 s]
[INFO] kivakit-serialization-gson 1.6.3-SNAPSHOT .......... SUCCESS [  0.001 s]
[INFO] kivakit-testing 1.6.3-SNAPSHOT ..................... SUCCESS [  0.001 s]
[INFO] kivakit-serialization-kryo-testing 1.6.3-SNAPSHOT .. SUCCESS [  0.001 s]
[INFO] kivakit-serialization 1.6.3-SNAPSHOT ............... SUCCESS [  0.000 s]
[INFO] kivakit-settings 1.6.3-SNAPSHOT .................... SUCCESS [  0.001 s]
[INFO] kivakit-network-core 1.6.3-SNAPSHOT ................ SUCCESS [  0.001 s]
[INFO] kivakit-network-socket 1.6.3-SNAPSHOT .............. SUCCESS [  0.000 s]
[INFO] kivakit-network-http 1.6.3-SNAPSHOT ................ SUCCESS [  0.002 s]
[INFO] kivakit-network-ftp 1.6.3-SNAPSHOT ................. SUCCESS [  0.015 s]
[INFO] kivakit-network-email 1.6.3-SNAPSHOT ............... SUCCESS [  0.001 s]
[INFO] kivakit-network 1.6.3-SNAPSHOT ..................... SUCCESS [  0.001 s]
[INFO] kivakit-component 1.6.3-SNAPSHOT ................... SUCCESS [  0.001 s]
[INFO] kivakit-application 1.6.3-SNAPSHOT ................. SUCCESS [  0.000 s]
[INFO] kivakit-internal-tests-core 1.6.3-SNAPSHOT ......... SUCCESS [  0.001 s]
[INFO] kivakit-internal-tests-resource 1.6.3-SNAPSHOT ..... SUCCESS [  0.002 s]
[INFO] kivakit-internal-tests 1.6.3-SNAPSHOT .............. SUCCESS [  0.000 s]
[INFO] kivakit-internal 1.6.3-SNAPSHOT .................... SUCCESS [  0.001 s]
[INFO] kivakit 1.6.3-SNAPSHOT ............................. SUCCESS [  0.000 s]
[INFO] cactus-graph 1.5.23 ................................ SUCCESS [  0.001 s]
[INFO] kivakit-settings-stores-zookeeper 1.6.3-SNAPSHOT ... SUCCESS [  0.001 s]
[INFO] kivakit-settings-stores 1.6.3-SNAPSHOT ............. SUCCESS [  0.000 s]
[INFO] kivakit-logs-file 1.6.3-SNAPSHOT ................... SUCCESS [  0.001 s]
[INFO] kivakit-logs-email 1.6.3-SNAPSHOT .................. SUCCESS [  0.000 s]
[INFO] kivakit-logs 1.6.3-SNAPSHOT ........................ SUCCESS [  0.000 s]
[INFO] kivakit-web-jetty 1.6.3-SNAPSHOT ................... SUCCESS [  0.001 s]
[INFO] kivakit-web-wicket 1.6.3-SNAPSHOT .................. SUCCESS [  0.000 s]
[INFO] kivakit-web-jersey 1.6.3-SNAPSHOT .................. SUCCESS [  0.001 s]
[INFO] kivakit-web-swagger 1.6.3-SNAPSHOT ................. SUCCESS [  0.001 s]
[INFO] kivakit-web 1.6.3-SNAPSHOT ......................... SUCCESS [  0.001 s]
[INFO] kivakit-filesystems-s3fs 1.6.3-SNAPSHOT ............ SUCCESS [  0.001 s]
[INFO] kivakit-filesystems-github 1.6.3-SNAPSHOT .......... SUCCESS [  0.001 s]
[INFO] kivakit-filesystems-java 1.6.3-SNAPSHOT ............ SUCCESS [  0.003 s]
[INFO] kivakit-filesystems 1.6.3-SNAPSHOT ................. SUCCESS [  0.001 s]
[INFO] kivakit-metrics-core 1.6.3-SNAPSHOT ................ SUCCESS [  0.001 s]
[INFO] kivakit-metrics-prometheus 1.6.3-SNAPSHOT .......... SUCCESS [  0.000 s]
[INFO] kivakit-metrics 1.6.3-SNAPSHOT ..................... SUCCESS [  0.001 s]
[INFO] kivakit-microservice 1.6.3-SNAPSHOT ................ SUCCESS [  0.047 s]
[INFO] kivakit-extensions 1.6.3-SNAPSHOT .................. SUCCESS [  0.001 s]
[INFO] kivakit-examples-application 1.6.3-SNAPSHOT ........ SUCCESS [  0.000 s]
[INFO] kivakit-examples-microservice 1.6.3-SNAPSHOT ....... SUCCESS [  0.001 s]
[INFO] kivakit-examples-settings 1.6.3-SNAPSHOT ........... SUCCESS [  0.001 s]
[INFO] kivakit-examples-lambda 1.6.3-SNAPSHOT ............. SUCCESS [  0.000 s]
[INFO] kivakit-examples 1.6.3-SNAPSHOT .................... SUCCESS [  0.001 s]
[INFO] kivakit-service-registry 1.6.3-SNAPSHOT ............ SUCCESS [  0.000 s]
[INFO] kivakit-service-client 1.6.3-SNAPSHOT .............. SUCCESS [  0.001 s]
[INFO] kivakit-logs-server 1.6.3-SNAPSHOT ................. SUCCESS [  0.001 s]
[INFO] kivakit-ui-desktop 1.6.3-SNAPSHOT .................. SUCCESS [  0.000 s]
[INFO] kivakit-primitive-collections 1.6.3-SNAPSHOT ....... SUCCESS [  0.001 s]
[INFO] kivakit-logs-client 1.6.3-SNAPSHOT ................. SUCCESS [  0.001 s]
[INFO] kivakit-logs-viewer 1.6.3-SNAPSHOT ................. SUCCESS [  0.001 s]
[INFO] kivakit-remote-log 1.6.3-SNAPSHOT .................. SUCCESS [  0.001 s]
[INFO] kivakit-filesystems-hdfs-proxy-spi 1.6.3-SNAPSHOT .. SUCCESS [  0.000 s]
[INFO] hadoop-doubly-shaded-protobuf 1.6.3-SNAPSHOT ....... SUCCESS [  0.001 s]
[INFO] kivakit-filesystems-hdfs-proxy 1.6.3-SNAPSHOT ...... SUCCESS [  0.001 s]
[INFO] kivakit-filesystems-hdfs 1.6.3-SNAPSHOT ............ SUCCESS [  0.001 s]
[INFO] kivakit-hdfs-filesystem 1.6.3-SNAPSHOT ............. SUCCESS [  0.002 s]
[INFO] kivakit-math 1.6.3-SNAPSHOT ........................ SUCCESS [  0.002 s]
[INFO] kivakit-security 1.6.3-SNAPSHOT .................... SUCCESS [  0.001 s]
[INFO] kivakit-ui 1.6.3-SNAPSHOT .......................... SUCCESS [  0.001 s]
[INFO] kivakit-data-compression 1.6.3-SNAPSHOT ............ SUCCESS [  0.001 s]
[INFO] kivakit-data-formats-library 1.6.3-SNAPSHOT ........ SUCCESS [  0.001 s]
[INFO] kivakit-data-formats-csv 1.6.3-SNAPSHOT ............ SUCCESS [  0.000 s]
[INFO] kivakit-data-formats-xml 1.6.3-SNAPSHOT ............ SUCCESS [  0.001 s]
[INFO] kivakit-data-formats 1.6.3-SNAPSHOT ................ SUCCESS [  0.001 s]
[INFO] kivakit-data 1.6.3-SNAPSHOT ........................ SUCCESS [  0.000 s]
[INFO] kivakit-service-server 1.6.3-SNAPSHOT .............. SUCCESS [  0.001 s]
[INFO] kivakit-service-viewer 1.6.3-SNAPSHOT .............. SUCCESS [  0.001 s]
[INFO] kivakit-service 1.6.3-SNAPSHOT ..................... SUCCESS [  0.000 s]
[INFO] kivakit-stuff 1.6.3-SNAPSHOT ....................... SUCCESS [  0.001 s]
[INFO] lexakai 1.0.11-SNAPSHOT ............................ SUCCESS [  0.000 s]
[INFO] mesakit-core 0.9.17-SNAPSHOT ....................... SUCCESS [  0.001 s]
[INFO] mesakit-map-shapefile 0.9.17-SNAPSHOT .............. SUCCESS [  0.001 s]
[INFO] mesakit-map-measurements 0.9.17-SNAPSHOT ........... SUCCESS [  0.000 s]
[INFO] mesakit-map-geography 0.9.17-SNAPSHOT .............. SUCCESS [  0.001 s]
[INFO] mesakit-map-data-library 0.9.17-SNAPSHOT ........... SUCCESS [  0.001 s]
[INFO] mesakit-map-data-formats-pbf 0.9.17-SNAPSHOT ....... SUCCESS [  0.001 s]
[INFO] mesakit-map-data-formats 0.9.17-SNAPSHOT ........... SUCCESS [  0.000 s]
[INFO] mesakit-map-data 0.9.17-SNAPSHOT ................... SUCCESS [  0.001 s]
[INFO] mesakit-map-utilities-geojson 0.9.17-SNAPSHOT ...... SUCCESS [  0.001 s]
[INFO] mesakit-map-utilities-geohash 0.9.17-SNAPSHOT ...... SUCCESS [  0.001 s]
[INFO] mesakit-map-utilities-grid 0.9.17-SNAPSHOT ......... SUCCESS [  0.001 s]
[INFO] mesakit-map-utilities 0.9.17-SNAPSHOT .............. SUCCESS [  0.001 s]
[INFO] mesakit-map-measurements-testing 0.9.17-SNAPSHOT ... SUCCESS [  0.002 s]
[INFO] mesakit-map-geography-testing 0.9.17-SNAPSHOT ...... SUCCESS [  0.002 s]
[INFO] mesakit-map-ui-desktop 0.9.17-SNAPSHOT ............. SUCCESS [  0.001 s]
[INFO] mesakit-map-ui-debug 0.9.17-SNAPSHOT ............... SUCCESS [  0.001 s]
[INFO] mesakit-map-region 0.9.17-SNAPSHOT ................. SUCCESS [  0.001 s]
[INFO] mesakit-map-road-model 0.9.17-SNAPSHOT ............. SUCCESS [  0.001 s]
[INFO] mesakit-map-region-testing 0.9.17-SNAPSHOT ......... SUCCESS [  0.002 s]
[INFO] mesakit-map-road-name-parser 0.9.17-SNAPSHOT ....... SUCCESS [  0.001 s]
[INFO] mesakit-map-road-name-standardizer 0.9.17-SNAPSHOT . SUCCESS [  0.001 s]
[INFO] mesakit-map-road 0.9.17-SNAPSHOT ................... SUCCESS [  0.001 s]
[INFO] mesakit-map-cutter 0.9.17-SNAPSHOT ................. SUCCESS [  0.020 s]
[INFO] mesakit-map-overpass 0.9.17-SNAPSHOT ............... SUCCESS [  0.001 s]
[INFO] mesakit-map-ui 0.9.17-SNAPSHOT ..................... SUCCESS [  0.001 s]
[INFO] mesakit-map 0.9.17-SNAPSHOT ........................ SUCCESS [  0.001 s]
[INFO] mesakit-graph-core 0.9.17-SNAPSHOT ................. SUCCESS [  0.000 s]
[INFO] mesakit-graph-query 0.9.17-SNAPSHOT ................ SUCCESS [  0.001 s]
[INFO] mesakit-graph-world 0.9.17-SNAPSHOT ................ SUCCESS [  0.001 s]
[INFO] mesakit-graph-core-testing 0.9.17-SNAPSHOT ......... SUCCESS [  0.000 s]
[INFO] mesakit-graph-world-testing 0.9.17-SNAPSHOT ........ SUCCESS [  0.001 s]
[INFO] mesakit-graph 0.9.17-SNAPSHOT ...................... SUCCESS [  0.000 s]
[INFO] mesakit-navigation-routing 0.9.17-SNAPSHOT ......... SUCCESS [  0.001 s]
[INFO] mesakit-navigation 0.9.17-SNAPSHOT ................. SUCCESS [  0.000 s]
[INFO] mesakit-internal-map-measurements-unit-tests 0.9.17-SNAPSHOT SUCCESS [  0.001 s]
[INFO] mesakit-internal-map-geography-unit-tests 0.9.17-SNAPSHOT SUCCESS [  0.000 s]
[INFO] mesakit-internal-map-region-unit-tests 0.9.17-SNAPSHOT SUCCESS [  0.001 s]
[INFO] mesakit-internal-graph-core-unit-tests 0.9.17-SNAPSHOT SUCCESS [  0.000 s]
[INFO] mesakit-internal 0.9.17-SNAPSHOT ................... SUCCESS [  0.001 s]
[INFO] mesakit 0.9.17-SNAPSHOT ............................ SUCCESS [  0.000 s]
[INFO] mesakit-geocoding 0.9.17-SNAPSHOT .................. SUCCESS [  0.001 s]
[INFO] mesakit-plugins-josm-library 0.9.17-SNAPSHOT ....... SUCCESS [  0.000 s]
[INFO] mesakit-plugins-josm-geojson 0.9.17-SNAPSHOT ....... SUCCESS [  0.001 s]
[INFO] mesakit-plugins-josm-graph 0.9.17-SNAPSHOT ......... SUCCESS [  0.000 s]
[INFO] mesakit-plugins-josm 0.9.17-SNAPSHOT ............... SUCCESS [  0.005 s]
[INFO] mesakit-plugins 0.9.17-SNAPSHOT .................... SUCCESS [  0.001 s]
[INFO] mesakit-serialization-json 0.9.17-SNAPSHOT ......... SUCCESS [  0.001 s]
[INFO] mesakit-serialization 0.9.17-SNAPSHOT .............. SUCCESS [  0.001 s]
[INFO] mesakit-tools-applications-graph-analyzer 0.9.17-SNAPSHOT SUCCESS [  0.001 s]
[INFO] mesakit-tools-applications-graph-double-digitized-ways-extractor 0.9.17-SNAPSHOT SUCCESS [  0.001 s]
[INFO] mesakit-tools-applications-graph-dumper 0.9.17-SNAPSHOT SUCCESS [  0.000 s]
[INFO] mesakit-tools-applications-graph-slicer 0.9.17-SNAPSHOT SUCCESS [  0.001 s]
[INFO] mesakit-tools-applications-graph-verifier 0.9.17-SNAPSHOT SUCCESS [  0.000 s]
[INFO] mesakit-tools-applications-graph-to-pbf-converter 0.9.17-SNAPSHOT SUCCESS [  0.001 s]
[INFO] mesakit-tools-applications-pbf-analyzer 0.9.17-SNAPSHOT SUCCESS [  0.000 s]
[INFO] mesakit-tools-applications-pbf-comparator 0.9.17-SNAPSHOT SUCCESS [  0.001 s]
[INFO] mesakit-tools-applications-pbf-dumper 0.9.17-SNAPSHOT SUCCESS [  0.000 s]
[INFO] mesakit-tools-applications-pbf-metadata 0.9.17-SNAPSHOT SUCCESS [  0.001 s]
[INFO] mesakit-tools-applications-pbf-region-extractor 0.9.17-SNAPSHOT SUCCESS [  0.000 s]
[INFO] mesakit-tools-applications-pbf-to-graph-converter 0.9.17-SNAPSHOT SUCCESS [  0.001 s]
[INFO] mesakit-tools-applications-pbf-world-graph-extractor 0.9.17-SNAPSHOT SUCCESS [  0.000 s]
[INFO] mesakit-tools-applications-pbf-filter 0.9.17-SNAPSHOT SUCCESS [  0.000 s]
[INFO] mesakit-tools-applications-codec-generator 0.9.17-SNAPSHOT SUCCESS [  0.001 s]
[INFO] mesakit-tools-applications-region-information 0.9.17-SNAPSHOT SUCCESS [  0.000 s]
[INFO] mesakit-tools-applications 0.9.17-SNAPSHOT ......... SUCCESS [  0.000 s]
[INFO] mesakit-tools-application-launcher 0.9.17-SNAPSHOT . SUCCESS [  0.001 s]
[INFO] mesakit-tools 0.9.17-SNAPSHOT ...................... SUCCESS [  0.000 s]
[INFO] mesakit-extensions 0.9.17-SNAPSHOT ................. SUCCESS [  0.001 s]
[INFO] mesakit-map-examples 0.9.17-SNAPSHOT ............... SUCCESS [  0.000 s]
[INFO] mesakit-examples 0.9.17-SNAPSHOT ................... SUCCESS [  0.001 s]
[INFO] telenav-build 2.0.2 ................................ SUCCESS [  1.594 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.032 s
[INFO] Finished at: 2022-08-11T17:31:05-06:00
[INFO] ------------------------------------------------------------------------
[~/Workspaces/telenav-build] cactus-pull-all-submodules
```

**Comment by timboudreau** [comment] 2022-08-11 23:51
What's the failure?  This just looks like you've already got everything on the server on the branches you're on.

```
[INFO] Nothing to pull. All projects are up to date with remote.
```

**Comment by timboudreau** [comment] 2022-08-12 00:22
Okay, to note:  The problem is we successfully test that there are no *remote* changes we do not have locally, but bail out if there no changes to move *over the wire* when there **are** changes *previously obtained from the remote* that have not been merged into the work tree.

Basically, in git, you're actually dealing with *three* copies of the code - the one on the remote server, the copy of the remote server's state in `.git`, and the state of your work-tree which may or may not be up-to-date with the last snapshot of the state from the server.

**Comment by timboudreau** [comment] 2022-08-12 02:15
Rewrote [`GitCheckout.needsPull()`](https://github.com/Telenav/cactus/blob/develop/cactus-git/src/main/java/com/telenav/cactus/git/GitCheckout.java#L807)

**Closed as completed by timboudreau** 2022-08-12 02:15 UTC
Labels: bug
